theme: jekyll-theme-minimal

title: " "
description: "Cloudless Skies: Decentralizing Mobile Interaction. Workshop at MobileHCI 2020, October 5th, Oldenburg, Germany"

logo: "cloudless.png"
show_downloads: false
