theme: jekyll-theme-minimal

title: "Cloudless Skies: Decentralizing Mobile Interaction"
description: "Workshop at MobileHCI 2020, October 5th, Oldenburg, Germany"

logo: "cloudless.png"
show_downloads: false
